version: "3"
services:
  elasticsearch:
    image: elasticsearch:6.5.4
    ports: 
      - "9200:9200"
      - "9300:9300"

    networks:
      - es-net

  kibana:
    image: kibana:6.5.4
    ports:
      - "5601:5601"
    
    networks:
      - es-net

networks: 
  es-net: